# Generated by Django 4.2.1 on 2023-12-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text_coments',
        ),
        migrations.AddField(
            model_name='comments',
            name='text_comments',
            field=models.TextField(default=1, max_length=2000, verbose_name='Текст коментария'),
            preserve_default=False,
        ),
    ]
